language: node_js
node_js:
 - "node"

cache: npm

script: yarn build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: 4fc49798c17131512618dd24b0c2231b05976741
 local_dir: docs
 on:
   branch: main