language: node_js
node_js:
 - "node"

cache: npm

script: yarn build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: ce6dc7aec411d9ab327849c9b604feeedfd68c7b
 local_dir: docs
 on:
   branch: main