language: node_js
node_js:
- node
cache: yarn
script: yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: W8RkyLRu1VrEEZNov0wr8ouWQT0h1A62H57j25XTQhVCG7Xb7rNU1Zqyj5Kv8xLyNKIxrJ5dRHCR2AR/Sv2PUV2aPqJxSrZBmLRNx38ZZL4rxC4wbDkG18gRcydH0kMkzgYjoMD/gFMKaryjdqZe+VVn7aBCYjpdD+NC4l/Kix7dFJYXOzr8k31rR9Qt38oYJ7QpORvLGbfgynruguZi+0VUeLqSRpcInBiLrXXbGmNDSqaUQ2p3t+ANxU6crnGzIhmnN3g8ujAYo3aA2oUXgvHcFpKuiqiE125RQKNGbr0r7g8PRwcee4ys9+F1id5TprQn0snAOtUsRJc6cqLSdfKwjjjx1SXm+5ajvedzpEU99VrZJAmlGYZBeOIurbyobINMgGOIel8iIdRtnleucMUEWNl/DrTpg31u5HTB5/61LuSqKr5JXrCNgsyxWGQq9MzOD/5ap9zYcAeUDRtg8rzbo5tHlgmg9QxvkwCi5SiPZ+KGPzEE6/1ui9fptvNdWTN0r5X0um9hwsvJotRNXpk7yv5Q1jgfK/NCV4HwGjzdFw91k+rP/7dpUJZWW732F2DlbxQxd22juYhd3Z2rOKuDr45CY3jchrzHgG/jd9HSmlMS21rZR326Fn8Y4eDV8IHQKX20Rp1zddrm+f06Yh6CIJvd4Eq5P8rACkQhmSQ=
  local_dir: docs
  on:
    branch: main
  token:
    secure: pgXx4VELEiVoRlcY5qoDOjDtagn/LSwp0s4U6+9Xlk7DKNkFH9RWx/Eu947EhELPUhyj5pTqqwbtPcUuyBmAlu5oQO+NdmB1Od2BgOkbSME0ZWDBsX5BpL6iMiybjAjVwK9ukfUyN2hDMOEZduMFMHYEVfNGa9VhloMqg8CsqXdvBNEH7MZP+juLGP1QaaFSHZFVCl36CuUIZ5TqVENOssSeXeEgOa6pUg9tcdSHCVTtsZzr0RGunlxwNR/OG/90tD69LTFDrtBoWOu6B2oO3mfTkqHAOw+q1emB8OOuXfiCsaO9xKyv1Taehjx1Rr/z6dGWEldUjXH/bsXlrPm51L5rIUJz0bGHpBBiyy8FeB0vW83092DS+nij7+1FQuZKr55rIFisqFtFA+Za2TsN7JQ211I3wxvBiQZ0FclGOzHFYTTomimmkCLqsn/0sMzy3JPTG8js90+6Y2Vh3DRTb5v90pRFkkIMusfee0iga+2T6/GLRKK+/PG5xVZUhVgKrt5DAN/O/sKPhQlxFeiH2oiyjBv2DkNuNhkOzzUIryjy4tEx54i/jCeU3ltli5HzQdAxwFlHHqkRtBd23UESXHZtFAgUjNaSkvXdPuIgCPbPIKY5Iiha/t4QDr6ifrCS8bDBwwzWcNCUrN50r1RL7KWnhF1nXWS65Y2qAsaXWv0=
